// <auto-generated />
using System;
using Email_data.Configs;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Email_data.Migrations
{
    [DbContext(typeof(EmailInteractionDbContext))]
    partial class EmailInteractionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Email_data.Models.Attachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EmailInteractionDetailsId")
                        .HasColumnType("int");

                    b.Property<bool>("IsInline")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedDateTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmailInteractionDetailsId");

                    b.ToTable("Attachment");
                });

            modelBuilder.Entity("Email_data.Models.EmailInteraction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConversationId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DraftInteractionId")
                        .HasColumnType("int");

                    b.Property<int>("EmailInteractionDetailsId")
                        .HasColumnType("int");

                    b.Property<string>("Queues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReplyToInteractionId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Top")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("DraftInteractionId");

                    b.HasIndex("EmailInteractionDetailsId")
                        .IsUnique();

                    b.ToTable("EmailInteractions");
                });

            modelBuilder.Entity("Email_data.Models.EmailInteractionDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BccRecipientsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("BccRecipients");

                    b.Property<string>("BodyPreview")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("Categories")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CcRecipientsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CcRecipients");

                    b.Property<string>("ChangeKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConversationId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConversationIndex")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FlagId")
                        .HasColumnType("int");

                    b.Property<string>("GraphId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasAttachments")
                        .HasColumnType("bit");

                    b.Property<string>("Importance")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InferenceClassification")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InternetMessageId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsDeliveryReceiptRequested")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDraft")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<bool>("IsReadReceiptRequested")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ParentFolderId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReceivedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReplyToJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ReplyTo");

                    b.Property<DateTime?>("SentDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToRecipientsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ToRecipients");

                    b.Property<string>("WebLink")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FlagId");

                    b.ToTable("EmailInteractionDetails");
                });

            modelBuilder.Entity("Email_data.Models.FollowupFlag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FlagStatus")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FollowupFlag");
                });

            modelBuilder.Entity("Email_data.Models.InternetMessageHeader", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("EmailInteractionDetailsId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmailInteractionDetailsId");

                    b.ToTable("InternetMessageHeader");
                });

            modelBuilder.Entity("Email_data.Models.Attachment", b =>
                {
                    b.HasOne("Email_data.Models.EmailInteractionDetails", null)
                        .WithMany("Attachments")
                        .HasForeignKey("EmailInteractionDetailsId");
                });

            modelBuilder.Entity("Email_data.Models.EmailInteraction", b =>
                {
                    b.HasOne("Email_data.Models.EmailInteraction", "DraftInteraction")
                        .WithMany()
                        .HasForeignKey("DraftInteractionId");

                    b.HasOne("Email_data.Models.EmailInteractionDetails", "EmailInteractionDetails")
                        .WithOne()
                        .HasForeignKey("Email_data.Models.EmailInteraction", "EmailInteractionDetailsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DraftInteraction");

                    b.Navigation("EmailInteractionDetails");
                });

            modelBuilder.Entity("Email_data.Models.EmailInteractionDetails", b =>
                {
                    b.HasOne("Email_data.Models.FollowupFlag", "Flag")
                        .WithMany()
                        .HasForeignKey("FlagId");

                    b.OwnsOne("Email_data.Models.EmailBody", "Body", b1 =>
                        {
                            b1.Property<int>("EmailInteractionDetailsId")
                                .HasColumnType("int");

                            b1.Property<string>("Content")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("ContentType")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("EmailInteractionDetailsId");

                            b1.ToTable("EmailInteractionDetails");

                            b1.WithOwner()
                                .HasForeignKey("EmailInteractionDetailsId");
                        });

                    b.OwnsOne("Email_data.Models.Recipient", "From", b1 =>
                        {
                            b1.Property<int>("EmailInteractionDetailsId")
                                .HasColumnType("int");

                            b1.HasKey("EmailInteractionDetailsId");

                            b1.ToTable("EmailInteractionDetails");

                            b1.WithOwner()
                                .HasForeignKey("EmailInteractionDetailsId");

                            b1.OwnsOne("Email_data.Models.EmailAddressEntity", "EmailAddress", b2 =>
                                {
                                    b2.Property<int>("RecipientEmailInteractionDetailsId")
                                        .HasColumnType("int");

                                    b2.Property<string>("Address")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("RecipientEmailInteractionDetailsId");

                                    b2.ToTable("EmailInteractionDetails");

                                    b2.WithOwner()
                                        .HasForeignKey("RecipientEmailInteractionDetailsId");
                                });

                            b1.Navigation("EmailAddress")
                                .IsRequired();
                        });

                    b.OwnsOne("Email_data.Models.Recipient", "Sender", b1 =>
                        {
                            b1.Property<int>("EmailInteractionDetailsId")
                                .HasColumnType("int");

                            b1.HasKey("EmailInteractionDetailsId");

                            b1.ToTable("EmailInteractionDetails");

                            b1.WithOwner()
                                .HasForeignKey("EmailInteractionDetailsId");

                            b1.OwnsOne("Email_data.Models.EmailAddressEntity", "EmailAddress", b2 =>
                                {
                                    b2.Property<int>("RecipientEmailInteractionDetailsId")
                                        .HasColumnType("int");

                                    b2.Property<string>("Address")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("RecipientEmailInteractionDetailsId");

                                    b2.ToTable("EmailInteractionDetails");

                                    b2.WithOwner()
                                        .HasForeignKey("RecipientEmailInteractionDetailsId");
                                });

                            b1.Navigation("EmailAddress")
                                .IsRequired();
                        });

                    b.OwnsOne("Email_data.Models.EmailBody", "UniqueBody", b1 =>
                        {
                            b1.Property<int>("EmailInteractionDetailsId")
                                .HasColumnType("int");

                            b1.Property<string>("Content")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("ContentType")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("EmailInteractionDetailsId");

                            b1.ToTable("EmailInteractionDetails");

                            b1.WithOwner()
                                .HasForeignKey("EmailInteractionDetailsId");
                        });

                    b.Navigation("Body")
                        .IsRequired();

                    b.Navigation("Flag");

                    b.Navigation("From")
                        .IsRequired();

                    b.Navigation("Sender")
                        .IsRequired();

                    b.Navigation("UniqueBody");
                });

            modelBuilder.Entity("Email_data.Models.FollowupFlag", b =>
                {
                    b.OwnsOne("Email_data.Models.DateTimeTimeZone", "CompletedDateTime", b1 =>
                        {
                            b1.Property<int>("FollowupFlagId")
                                .HasColumnType("int");

                            b1.Property<DateTime?>("DateTime")
                                .HasColumnType("datetime2");

                            b1.Property<string>("TimeZone")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("FollowupFlagId");

                            b1.ToTable("FollowupFlag");

                            b1.WithOwner()
                                .HasForeignKey("FollowupFlagId");
                        });

                    b.OwnsOne("Email_data.Models.DateTimeTimeZone", "DueDateTime", b1 =>
                        {
                            b1.Property<int>("FollowupFlagId")
                                .HasColumnType("int");

                            b1.Property<DateTime?>("DateTime")
                                .HasColumnType("datetime2");

                            b1.Property<string>("TimeZone")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("FollowupFlagId");

                            b1.ToTable("FollowupFlag");

                            b1.WithOwner()
                                .HasForeignKey("FollowupFlagId");
                        });

                    b.OwnsOne("Email_data.Models.DateTimeTimeZone", "StartDateTime", b1 =>
                        {
                            b1.Property<int>("FollowupFlagId")
                                .HasColumnType("int");

                            b1.Property<DateTime?>("DateTime")
                                .HasColumnType("datetime2");

                            b1.Property<string>("TimeZone")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("FollowupFlagId");

                            b1.ToTable("FollowupFlag");

                            b1.WithOwner()
                                .HasForeignKey("FollowupFlagId");
                        });

                    b.Navigation("CompletedDateTime");

                    b.Navigation("DueDateTime");

                    b.Navigation("StartDateTime");
                });

            modelBuilder.Entity("Email_data.Models.InternetMessageHeader", b =>
                {
                    b.HasOne("Email_data.Models.EmailInteractionDetails", null)
                        .WithMany("InternetMessageHeaders")
                        .HasForeignKey("EmailInteractionDetailsId");
                });

            modelBuilder.Entity("Email_data.Models.EmailInteractionDetails", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("InternetMessageHeaders");
                });
#pragma warning restore 612, 618
        }
    }
}
